=== KZsolt11/portal_game/src/main/resources/dtd.dtd
<!ELEMENT Maze (Items?,Walls?)>
<!ELEMENT Items (Hole*,ZPM*,Scale*, Box*)>
<!ELEMENT Hole (#PCDATA)>
<!ELEMENT ZPM (#PCDATA)>
<!ELEMENT Scale (#PCDATA)>
<!ELEMENT Box (#PCDATA)>
<!ELEMENT Walls (Wall*)>
<!ELEMENT Wall (#PCDATA)>

<!ATTLIST Maze	height CDATA #REQUIRED>
<!ATTLIST Maze	width CDATA #REQUIRED>
<!ATTLIST Maze	name CDATA #REQUIRED>

<!ATTLIST Hole	posX CDATA #REQUIRED>
<!ATTLIST Hole	posY CDATA #REQUIRED>

<!ATTLIST ZPM	posX CDATA #REQUIRED>
<!ATTLIST ZPM	posY CDATA #REQUIRED>

<!ATTLIST Box	posX CDATA #REQUIRED>
<!ATTLIST Box	posY CDATA #REQUIRED>
<!ATTLIST Box	weight CDATA "1">


<!ATTLIST Scale	posX CDATA #REQUIRED>
<!ATTLIST Scale	posY CDATA #REQUIRED>
<!ATTLIST Scale	id CDATA #REQUIRED>

<!ATTLIST Wall	posX CDATA #REQUIRED>
<!ATTLIST Wall posY CDATA #REQUIRED>
<!ATTLIST Wall	isSpecial CDATA "false">
<!ATTLIST Wall hasDoor CDATA "false">
<!ATTLIST Wall scaleID CDATA #IMPLIED>
<!ATTLIST Wall orientation CDATA #REQUIRED>

=== KZsolt11/portal_game/bin/XML_4_test.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Maze SYSTEM "dtd.dtd">
<Maze name="Test4" height="20" width="20">
<Items>
		<Hole posX="5" posY="4"/>
		<ZPM posX="8" posY="4"/>
		<ZPM posX="16" posY="6"/>
		<ZPM posX="2" posY="5"/>
		<ZPM posX="8" posY="17"/>
		<ZPM posX="3" posY="10"/>
		<ZPM posX="17" posY="18"/>
		<ZPM posX="14" posY="19"/>
		<ZPM posX="19" posY="15"/>
		<ZPM posX="8" posY="9"/>
		<ZPM posX="1" posY="7"/>
		<ZPM posX="7" posY="6"/>
		<Scale posX="15" posY="14" id="1"/>
		<Box posX="15" posY="10" weight="6"/>
		<Box posX="19" posY="3" weight="7"/>
</Items>
	<Walls>
		<Wall posX="6" posY="4" isSpecial="false" hasDoor="true" scaleID="1" orientation="2"/>
		<Wall posX="9" posY="4" isSpecial="true" hasDoor="false" orientation="2"/>
		<Wall posX="19" posY="18" isSpecial="true" hasDoor="false" orientation="3"/>
		<Wall posX="2" posY="4" isSpecial="false" hasDoor="false" orientation="1"/>
		<Wall posX="2" posY="4" isSpecial="false" hasDoor="false" orientation="3"/>
		<Wall posX="3" posY="4" isSpecial="false" hasDoor="false" orientation="1"/>
		<Wall posX="3" posY="4" isSpecial="false" hasDoor="false" orientation="3"/>
		<Wall posX="4" posY="4" isSpecial="false" hasDoor="false" orientation="1"/>
		<Wall posX="4" posY="4" isSpecial="false" hasDoor="false" orientation="3"/>
		<Wall posX="5" posY="4" isSpecial="false" hasDoor="false" orientation="1"/>
		
		<Wall posX="5" posY="4" isSpecial="false" hasDoor="false" orientation="3"/>
		<Wall posX="6" posY="4" isSpecial="false" hasDoor="false" orientation="1"/>
		<Wall posX="6" posY="4" isSpecial="false" hasDoor="false" orientation="3"/>
		<Wall posX="7" posY="4" isSpecial="false" hasDoor="false" orientation="1"/>
		<Wall posX="7" posY="4" isSpecial="false" hasDoor="false" orientation="3"/>
		<Wall posX="8" posY="4" isSpecial="false" hasDoor="false" orientation="1"/>
		<Wall posX="8" posY="4" isSpecial="false" hasDoor="false" orientation="3"/>
		
		<Wall posX="9" posY="4" isSpecial="false" hasDoor="false" orientation="1"/>
		<Wall posX="9" posY="4" isSpecial="false" hasDoor="false" orientation="3"/>
		<Wall posX="10" posY="4" isSpecial="false" hasDoor="false" orientation="1"/>
		<Wall posX="10" posY="4" isSpecial="false" hasDoor="false" orientation="3"/>
		<Wall posX="11" posY="4" isSpecial="false" hasDoor="false" orientation="1"/>
		<Wall posX="11" posY="4" isSpecial="false" hasDoor="false" orientation="3"/>
		<Wall posX="12" posY="4" isSpecial="false" hasDoor="false" orientation="1"/>
		<Wall posX="12" posY="4" isSpecial="false" hasDoor="false" orientation="3"/>
		<Wall posX="12" posY="4" isSpecial="false" hasDoor="false" orientation="2"/>
	</Walls>
	
</Maze>

=== KZsolt11/portal_game/src/main/resources/XML_2.1_test.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Maze SYSTEM "dtd.dtd">
<Maze name="Test2.1" height="1" width="3">
	<Items>
		<Hole posX="2" posY="0"/>
	</Items>
	<Walls>
		<Wall posX="0" posY="0" isSpecial="false" hasDoor="false" orientation="3"/>
		<Wall posX="0" posY="0" isSpecial="false" hasDoor="false" orientation="1"/>
		<Wall posX="0" posY="0" isSpecial="true" hasDoor="false" orientation="4"/>
		<Wall posX="1" posY="0" isSpecial="true" hasDoor="false" orientation="1"/>
		<Wall posX="1" posY="0" isSpecial="false" hasDoor="false" orientation="3"/>
		<Wall posX="2" posY="0" isSpecial="false" hasDoor="false" orientation="1"/>
		<Wall posX="2" posY="0" isSpecial="false" hasDoor="false" orientation="2"/>
		<Wall posX="2" posY="0" isSpecial="false" hasDoor="false" orientation="3"/>
	</Walls>
	
</Maze>

=== KZsolt11/portal_game/bin/XML_3_test.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Maze SYSTEM "dtd.dtd">
<Maze name="Test3" height="3" width="2">
<Items>
		<Hole posX="1" posY="2"/>
		<Box posX="0" posY="1" weight="3"/>
		<Box posX="1" posY="0" weight="1"/>
</Items>
	<Walls>
		<Wall posX="0" posY="0" isSpecial="false" hasDoor="false" orientation="1"/>
		<Wall posX="0" posY="0" isSpecial="false" hasDoor="false" orientation="4"/>
		<Wall posX="1" posY="0" isSpecial="true" hasDoor="false" orientation="1"/>
		<Wall posX="1" posY="0" isSpecial="false" hasDoor="false" orientation="2"/>
		<Wall posX="0" posY="1" isSpecial="false" hasDoor="false" orientation="4"/>
		<Wall posX="0" posY="1" isSpecial="false" hasDoor="false" orientation="3"/>
		<Wall posX="1" posY="1" isSpecial="false" hasDoor="false" orientation="2"/>
		<Wall posX="1" posY="2" isSpecial="false" hasDoor="false" orientation="2"/>
		<Wall posX="1" posY="2" isSpecial="false" hasDoor="false" orientation="3"/>
		<Wall posX="1" posY="2" isSpecial="false" hasDoor="false" orientation="4"/>
	</Walls>
	
</Maze>
